version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: "sudo /bin/sh -c 'wget https://github.com/benchkram/bob/releases/download/0.5.3/bob_0.5.3_linux_amd64 -O /usr/local/bin/bob && chmod +x /usr/local/bin/bob'"
      - run: bob --version
workflows:
  run-bob-version:
    jobs:
      - build
